project:
  type: website
  output-dir: docs

website:
  title: "Sydney Informatics Hub Intro to Omeka S"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Basic concepts"
          href: notebooks/01_basic_concepts.html
        - text: "Uploading resources"
          href: notebooks/02_upload_resources.html
        - text: "Linking resources"
          href: notebooks/03_linking_resources.html
        - text: "Creating a site"
          href: notebooks/04_create_a_site.html
        - text: "Create a map"
          href: notebooks/05_create_a_map.html
        - text: "Site navigation"
          href: notebooks/06_site_navigation.html
        - text: "Mapping by links"
          href: notebooks/07_map_by_links.html
  cookie-consent:
    type: express
    style: simple
    palette: light
    policy-url: https://www.sydney.edu.au/privacy-statement.html
  google-analytics: "G-TNWWV3HK57"

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

format:
  html:
   toc: true
   theme:
      light: flatly
      dark: darkly
   css: styles.scss
   code-link: true
   code-fold: false


